language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: OfsrAtLk1pdpdtyc8J2nLeLZhNT8lPyhKN4TkBXvnWKMMgz6IGjI69ArHJ4lKrdoXXgCQZI932wW1N4h4skg6W3OE6hTIju2mb1mUcpvKD7nBj+9EJBa4cabkObIGzroS8bzCDoUU7yGocxviNnxsSAiVnP9W197Hczywz2cklGn3MHFdg8xPiXXoLSA43rG6tTuD/UpdodaQDOwydryRWUr1sU43VvfE/0yA0I66+1HrIqxyvvnZu0JqQGEH7AypkJUQxNv//WCnEuh6oNNFWKUfUZgh2GHf/irAV2TH+OYt+jPFpkNrn90ez2AL9Qg54gJZTLSlVbife+Jd1KozpfFKPYXBeofWeLtkXjeGJNOHn0qu6VHe7KFh6jAK34ZYGc6iZfWqRmpuuU6bL83iSuqPxAiRvEViPMNAU3Y9ADFMVteqbc0WMGg43AGM5co9BIRzRYyuMF/Jk/hROKAX/7/KxF26R7i3eKIXyKSdaoYVjBJTXKjwpKwkezlERDWEhlS5SRcEFcMXbhAztJTkBjdLln7XRvGjf1wAwPfIDITic+aLNl1nCygh9wTPpLs3y34JaAV7wXTdi8V0soJvhYidJQdt0XgB2lltOTIy2C+wuk0At6o7Db+0frdSXRApBD+TnVChzdFpjOfkr+sVOtLHFQV/J91OJoYeSIuHas=
